    <br/>
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h2><img src="/images/kissapi_logo_final.png"/><br/> Photo Collage</h2>
            <ul>
            <li>Login to Facebook</li>
            <li>Choose your favoriate photos</li>
            <li>Wait and watch the magic happen</li>
            <li>Show the collage to your friends</li>
            <li>Be happy</li>
            </ul>
		<fb:login-button show-faces="true" width="400" max-rows="1" scope="user_photos,friends_photos,publish_stream"></fb:login-button><br/><br/>
		<div class="fb-like" data-href="http://www.kissapi.com" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true" data-font="arial"></div>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Collage</h2>
            <img src="https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/41738351831371/collage/b2a5f67bfb84f961c487d06783885c6b92a24fa3"/>
            <p>Easily create collages of your favoriate photos from Facebook and then repost them onto your wall for everyone to enjoy.  This is using HP's awesome photo colloage API but you dont have to learn it to use it.  Just click here!</p>
          <p><a class="btn" href="/collage/photos">Make Me a Collage! &raquo;</a></p>


        </div>
        <div class="span4">
          <h2>Locating Friends</h2>
            <p>Every have the problem of meeting up with a friend or a group of friends and you guys are always texting or calling each other to see where everyone is?  This app is here to solve this very problem.  You just have to give each of your friend a URL via text, email or another other means and from there everyone would be plotted on a map so you guys can find each other even if you guys are still on the move.</p>
          <p><a class="btn" href="#">Coming Soon &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Games</h2>
            <p>Coming soon, we are making some very awesome Javascript games in a 3D world where all your friends can join, that will blow your mind away.</p>
          <p><a class="btn" href="#">Coming Soon &raquo;</a></p>
        </div>
      </div>

      <hr>

