
<style>

/*Lets start with the cloud formation rather*/

/*The container will also serve as the SKY*/

*{ margin: 0; padding: 0;}

body {
	/*To hide the horizontal scroller appearing during the animation*/
	overflow: hidden;
}


#clouds{
	padding: 100px 0;
	position: fixed;
	z-index: -1;
	
}

/*Time to finalise the cloud shape*/
.cloud {
	width: 200px; height: 60px;
	background: #fff;
	
	border-radius: 200px;
	-moz-border-radius: 200px;
	-webkit-border-radius: 200px;
	
	position: relative; 
}

.cloud:before, .cloud:after {
	content: '';
	position: absolute; 
	background: #fff;
	width: 100px; height: 80px;
	position: absolute; top: -15px; left: 10px;
	
	border-radius: 100px;
	-moz-border-radius: 100px;
	-webkit-border-radius: 100px;
	
	-webkit-transform: rotate(30deg);
	transform: rotate(30deg);
	-moz-transform: rotate(30deg);
}

.cloud:after {
	width: 120px; height: 120px;
	top: -55px; left: auto; right: 15px;
}

/*Time to animate*/
.x1 {
	-webkit-animation: moveclouds 15s linear infinite;
	-moz-animation: moveclouds 15s linear infinite;
	-o-animation: moveclouds 15s linear infinite;
}

/*variable speed, opacity, and position of clouds for realistic effect*/
.x2 {
	left: 200px;
	
	-webkit-transform: scale(0.6);
	-moz-transform: scale(0.6);
	transform: scale(0.6);
	opacity: 0.6; /*opacity proportional to the size*/
	
	/*Speed will also be proportional to the size and opacity*/
	/*More the speed. Less the time in 's' = seconds*/
	-webkit-animation: moveclouds 25s linear infinite;
	-moz-animation: moveclouds 25s linear infinite;
	-o-animation: moveclouds 25s linear infinite;
}

.x3 {
	left: -250px; top: -200px;
	
	-webkit-transform: scale(0.8);
	-moz-transform: scale(0.8);
	transform: scale(0.8);
	opacity: 0.8; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 20s linear infinite;
	-moz-animation: moveclouds 20s linear infinite;
	-o-animation: moveclouds 20s linear infinite;
}

.x4 {
	left: 470px; top: -250px;
	
	-webkit-transform: scale(0.75);
	-moz-transform: scale(0.75);
	transform: scale(0.75);
	opacity: 0.75; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 18s linear infinite;
	-moz-animation: moveclouds 18s linear infinite;
	-o-animation: moveclouds 18s linear infinite;
}

.x5 {
	left: -150px; top: -150px;
	
	-webkit-transform: scale(0.8);
	-moz-transform: scale(0.8);
	transform: scale(0.8);
	opacity: 0.8; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 20s linear infinite;
	-moz-animation: moveclouds 20s linear infinite;
	-o-animation: moveclouds 20s linear infinite;
}

@-webkit-keyframes moveclouds {
	0% {margin-left: 1400px;}
	100% {margin-left: -1400px;}
}
@-moz-keyframes moveclouds {
	0% {margin-left: 1400px;}
	100% {margin-left: -1400px;}
}
@-o-keyframes moveclouds {
	0% {margin-left: 1400px;}
	100% {margin-left: -1400px;}
}
</style>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">
<div id="banner_bg" style="background-image:url('/images/main_bg.png'); background-repeat: repeat-x; height: 517px; width: 100%; position: absolute; z-index: -2;"></div>
	<div id="clouds">
	<div class="cloud x1"></div>
	<!-- Time for multiple clouds to dance around -->
	<div class="cloud x2"></div>
	<div class="cloud x3"></div>
	<div class="cloud x4"></div>
	<div class="cloud x5"></div>

	</div>
<div class="container">
      <div class="row-fluid">
        <div class="span6"><div style="position: relative; top: 150px;"><img src="/images/kissapi_logo_final.png"/><strong style="padding-left: 166px; color: #e20060; font-size: 32px; font-family: 'Lato','serif';">create fun stuff</strong>
	
		<br><br><div style="padding-left: 200px;"><fb:login-button show-faces="true" width="200" max-rows="1" scope="user_photos,friends_photos,publish_stream"></fb:login-button><br/><br/>
		<div class="fb-like" data-href="http://www.kissapi.com" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true" data-font="arial"></div></div>

		</div>
	</div>
        <div class="span6" style="height: 517px;">
          <div style="position: relative; top: 150px;"><h2>Create A Photo Collage</h2>
	    <ul>
            <li>Login to Facebook</li>
            <li>Choose your favorite photos</li>
            <li>Wait and watch the magic happen</li>
            <li>Show the collage to your friends</li>
            <li>Be happy</li>
            </ul>

          <p><a class="btn btn-large" href="/collage/photos">Get Started &raquo;</a></p>
	  </div>

        </div>
      </div>


</div>
	<div style="background-color: #2899fe; width: 100%; bottom-border: 1px solid #2594f7"></div>
