<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          Select pictures you want in the collage, then click this button: 
	  <button class="btn btn-large btn-primary" id="button" type="button" href="javascript:void(0);" onclick="$('#generate_collage').submit(); $('#button').button('loading');" data-loading-text="...Generating..." >Generate Collage</button>
        </div>
      </div>
    </div>

    <div class="row-fluid">
    <form id="generate_collage" method="POST" action="/collage/generate">

<?php
    // Display the user's images

    foreach( $this->mePhotos['data'] as $aPic ){

        echo '<div class="span4">';
        echo '<img src="' . $aPic['images'][4]['source'] . '"/><br/>';
//        echo '<input type="checkbox" name="pic[]" value="'.$aPic['id'].'"> Select<br>';
        echo '<input type="checkbox" name="pic[]" value="'.$aPic['images'][4]['source'] .'"> Select<br>';
        echo '</div>';
    }

?>
    </form>
    </div>
